services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest

    container_name: jellyfin

    user: "1000:1000"

    runtime: nvidia

    network_mode: host

    restart: unless-stopped

    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      JELLYFIN_CACHE_DIR: /var/cache/jellyfin
      JELLYFIN_CONFIG_DIR: /etc/jellyfin
      JELLYFIN_DATA_DIR: /var/lib/jellyfin
      JELLYFIN_LOG_DIR: /var/log/jellyfin

    volumes:
      - /data/jellyfin/cache:/var/cache/jellyfin
      - /data/jellyfin/config:/etc/jellyfin
      - /data/jellyfin/lib:/var/lib/jellyfin
      - /var/log/jellyfin:/var/log/jellyfin
      - type: bind
        source: /nas/0/movies
        target: /media/movies
        read_only: true
      - type: bind
        source: /nas/0/shows
        target: /media/shows
        read_only: true

