services:
  jellyfin:
    image: jellyfin-jetson
    #entrypoint: ["/bin/bash", "-c", "jellyfin"]

    container_name: jellyfin-jetson

    #user: "1000:1000"

    runtime: nvidia

    network_mode: host

    restart: unless-stopped

    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      JELLYFIN_CACHE_DIR: /var/cache/jellyfin
      JELLYFIN_CONFIG_DIR: /etc/jellyfin
      JELLYFIN_DATA_DIR: /var/lib/jellyfin
      JELLYFIN_LOG_DIR: /var/log/jellyfin

    volumes:
      - /data/jellyfin/cache:/var/cache/jellyfin
      - /data/jellyfin/config:/etc/jellyfin
      - /data/jellyfin/lib:/var/lib/jellyfin
      - /var/log/jellyfin:/var/log/jellyfin
      - type: bind
        source: /nas/0/movies
        target: /media/movies
        read_only: true
      - type: bind
        source: /nas/0/shows
        target: /media/shows
        read_only: true

    #healthcheck:
      #test: ["CMD", "curl", "--noproxy", "\"localhost\"", "-Lk", "-fsS", "\"http://localhost:8096/health\""]
      #interval: 30s
      #timeout: 30s
      #start_period: 10s
      #start_interval: 0s
      #retries: 3
