---
version: "3.8"
services:
  dashy:
    container_name: Dashy

    image: lissy93/dashy

    volumes:
      - /home/xavier/podman/dashy/config.yml:/app/user-data/conf.yml
      - /home/xavier/podman/dashy/item-icons:/app/user-data/item-icons/

    ports:
      - 80:8080

    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000

    # Specify restart policy
    restart: unless-stopped

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 4m

